######################################################################
##
## Filename: centiseconds.udo
## Created on: Thu Jul 04 3:11:30 PM GTB Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
