######################################################################
##
## Filename: clockgen.udo
## Created on: Thu Jul 04 8:41:22 AM GTB Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
