######################################################################
##
## Filename: counter9.udo
## Created on: Thu Jul 04 2:07:09 PM GTB Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
