######################################################################
##
## Filename: counter250k.udo
## Created on: Thu Jul 04 2:27:37 PM GTB Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
